"""empty message

Revision ID: 06b755a697f7
Revises: 
Create Date: 2024-06-25 12:19:55.228291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06b755a697f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=True))
    op.execute('UPDATE todos SET completed = false WHERE completed IS Null')

    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.alter_column('completed',existing_type=sa.Boolean(),nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.drop_column('completed')

    # ### end Alembic commands ###
